# This yaml file is used to automatically configure the jobs.

jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  globalNodeProperties:
    - envVars:
        env:
          - key: VARIABLE1
            value: localhost
          - key: VARIABLE2
            value: 8080
  views:
    - list:
        jobNames:
          - "pipeline-job"
        name: "GitHub"
    - list:
        jobNames:
          - "freestyle-job"
        name: "Others"

tool:
  git:
    installations:
      - name: git
        home: git

  maven:
    installations:
      - name: maven
        home: /usr/bin/mvn

  jdk:
    installations:
      - name: java11
        home: /usr/bin/java

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: my-credential
              description: "My Username/Password Credential"
              username: myusername
              password: mypassword

jobs:
  - script: >
      pipelineJob('pipeline-job') {
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              github('varuntawade/Jenkins')
                          }
                      }
                  }
                  scriptPath('Configuration_as_Code/pipeline_job.groovy')
              }
          }
      }

  - script: >
      job('freestyle-job') {
          steps {
            shell("""
                echo "The current build number is \$BUILD_NUMBER"
                echo "The current build ID is \$BUILD_ID"
                echo "The Job Name is \$JOB_NAME"
                echo "The Domain name is \$VARIABLE1"
                echo "The port number is \$VARIABLE2"
            """)
          }
      }
